### ISSUE TITLE
Parsing Cases for clean_data DataCleaner() no longer works 

### ISSUE THREAD

**Issue by JJModern** [michplunkett/supreme-court-ml-predictions#21]
Parsing Cases for clean_data DataCleaner() no longer works.

Before, DataCleaner() was working. 

Parsing cases...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "base_directory/supreme-court-ml-predictions/supreme_court_predictions/__main__.py", line 48, in <module>
    clean_data()
  File "base_directory/supreme-court-ml-predictions/supreme_court_predictions/statistics/service.py", line 11, in clean_data
    DataCleaner(downloaded_corpus=True, save_data=True).parse_all_data()
  File "base_directory/supreme-court-ml-predictions/supreme_court_predictions/statistics/datacleaner.py", line 256, in parse_all_data
    cases_list = self.load_data("cases.jsonl")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_directory/supreme-court-ml-predictions/supreme_court_predictions/statistics/datacleaner.py", line 73, in load_data
    with open(
         ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'base_directory/supreme-court-ml-predictions/supreme_court_predictions/data/convokit/supreme_corpus/cases.jsonl'
make: *** [clean-data] Error 1

**Comment by JJModern** [comment]
get_data() function has since been updated to require cases.jsonl
